# Generated by Django 6.0.1 on 2026-02-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movielist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='uu_id',
        ),
    ]
