# Generated by Django 6.0.1 on 2026-02-09 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_movie_uu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
